spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/hotdesking_db}
    username: ${DB_USER:hoang}
    password: ${DB_PASS:default_pass}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  data:
    redis:
      host: localhost
      port: 6379

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - email
              - profile
server:
  port: 8080